# This is a basic workflow to help you get started with Actions

name: Build 5.15.y

on:
  workflow_dispatch:
  #schedule:
    #- cron: "36 19 * * 2,6"
    
env:
  UPLOAD_RELEASE: true
  TZ: Asia/Jakarta

jobs:
  build_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build Kernel
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Run commands
        env:
          DEBIAN_FRONTEND: noninteractive
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          env: |
            REPO_KERNEL: https://github.com/unifreq/linux-5.15.y
            REPO_BRANCH: main
            CONFIG_URL: https://raw.githubusercontent.com/radityabh/kernel-compiler/main/config/kernel-5.15.y/.config
          
          # The shell to run commands with in the container
          shell: /bin/sh
          
          install: |
            apt-get -qq update
            apt-get -qq install curl wget build-essential libncurses-dev bison flex libssl-dev libelf-dev git
            apt-get -qq autoremove --purge
            apt-get -qq clean
            ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            git clone --depth 1 ${REPO_KERNEL} -b ${REPO_BRANCH} kernel
            cd kernel
            wget -O .config ${CONFIG_URL}
            echo -e "$(nproc) thread compile"


      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
