# This is a basic workflow to help you get started with Actions

name: Build 5.15.y

on:
  workflow_dispatch:
  #schedule:
    #- cron: "36 19 * * 2,6"
    
env:
  REPO_KERNEL: https://github.com/unifreq/linux-5.15.y
  REPO_BRANCH: main
  UPLOAD_RELEASE: true
  TZ: Asia/Jakarta

jobs:
  build_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build Kernel
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}
          
          # The shell to run commands with in the container
          shell: /bin/sh
          
          install: |
            apt-get -qq update
            apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804) rdate build-essential libncurses-dev bison flex libssl-dev libelf-dev
            apt-get -qq autoremove --purge
            apt-get -qq clean
            ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          
          clone: |
            git clone --depth 1 $REPO_URL -b $REPO_BRANCH kernel

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            cd kernel
            ls
            uname -a
            echo ::set-output name=uname::$(uname -a)

      - name: Get the output
        # Echo the `uname` output parameter from the `runcmd` step
        run: |
          echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
