# This is a basic workflow to help you get started with Actions

name: Build initrd

on:
  workflow_dispatch:
  #schedule:
    #- cron: "36 19 * * 2,6"
    
env:
  UPLOAD_RELEASE: true
  TZ: Asia/Jakarta

jobs:
  build_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build Kernel
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Run commands
        env:
          DEBIAN_FRONTEND: noninteractive
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu18.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          env: |
            REPO_KERNEL: https://github.com/unifreq/linux-5.15.y
            REPO_BRANCH: main
            CONFIG_URL: https://raw.githubusercontent.com/radityabh/kernel-compiler/main/config/kernel-5.15.y/coba.config
          
          # The shell to run commands with in the container
          shell: /bin/bash
          
          install: |
            apt-get -qq update
            apt-get -qq install curl wget build-essential libncurses-dev bison flex libssl-dev libelf-dev git u-boot-tools
            apt-get -qq autoremove --purge
            apt-get -qq clean
            ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

          # Set an output parameter `uname` for use in subsequent steps
          run: |
            wget https://github.com/radityabh/kernel-compiler/releases/download/Amlogic_Kernel_5.15.13_latest_arm64_2022.01.07-1624/linux-image-5.4.170-raditbh_5.4.170-raditbh-1_arm64.deb
            dpkg -i linux-image-5.4.170-raditbh_5.4.170-raditbh-1_arm64.deb
            dest="out"
            rm -rf ${dest}
            mkdir -p ${dest}
            cd /boot
            cp config-${kver} ${PWD}/${dest}
            cp initrd.img-${kver} ${PWD}/${dest}
            cp uInitrd-${kver} ${PWD}/${dest}
            cp config-${kver} ${PWD}/${dest}
            cp vmlinuz-${kver} ${PWD}/${dest}
            echo "PACKAGED_OUTPUTPATH=${PWD}/${dest}" >> $GITHUB_ENV
            echo "::set-output name=status::success"

      - name: Upload Firmware Files to GitHub Release
        uses: ncipollo/release-action@v1
        if: steps.build.outputs.status == 'success' && !cancelled()
        with:
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Test Kernel
          tag: test-kernel
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}
